"""Add source_path to LearningResource

Revision ID: 2d09a8ce10d3
Revises: dc7034d6ba93
Create Date: 2026-05-30 11:41:16.792612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d09a8ce10d3'
down_revision: Union[str, Sequence[str], None] = 'dc7034d6ba93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_path', sa.String(length=1024), nullable=True))
        batch_op.create_index(batch_op.f('ix_learning_resource_source_path'), ['source_path'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_resource', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_resource_source_path'))
        batch_op.drop_column('source_path')

    # ### end Alembic commands ###
