"""create_quiz_table

Revision ID: 6c3afdd91dfb
Revises: d326487bc9ca
Create Date: 2026-05-30 12:01:52.419892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import backend
import backend.app.core.database



# revision identifiers, used by Alembic.
revision: str = '6c3afdd91dfb'
down_revision: Union[str, Sequence[str], None] = 'd326487bc9ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('resource_id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['learning_resource.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz')
    # ### end Alembic commands ###
