"""add_inactive_seconds_to_session

Revision ID: 9bd4577cf6f2
Revises: c8b5c0cd3cf0
Create Date: 2026-05-31 18:06:25.024073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bd4577cf6f2'
down_revision: Union[str, Sequence[str], None] = 'c8b5c0cd3cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inactive_seconds', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('media_progress', schema=None) as batch_op:
        batch_op.alter_column('last_position',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_progress', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('last_position',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('learning_session', schema=None) as batch_op:
        batch_op.drop_column('inactive_seconds')

    # ### end Alembic commands ###
