"""Add MediaAsset and MediaProgress tables

Revision ID: c15454b31b32
Revises: 2d09a8ce10d3
Create Date: 2026-05-30 11:52:40.417660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import backend
import backend.app.core.database


# revision identifiers, used by Alembic.
revision: str = 'c15454b31b32'
down_revision: Union[str, Sequence[str], None] = '2d09a8ce10d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_asset',
    sa.Column('id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('resource_id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('lesson_id', backend.app.core.database.GUID(), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['learning_resource.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_asset_file_path'), ['file_path'], unique=True)

    op.create_table('media_progress',
    sa.Column('id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('media_asset_id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('last_position', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('is_watched', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_asset_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_progress')
    with op.batch_alter_table('media_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_asset_file_path'))

    op.drop_table('media_asset')
    # ### end Alembic commands ###
