"""create_knowledge_tables

Revision ID: c8b5c0cd3cf0
Revises: e0ae5104d8d2
Create Date: 2026-05-30 12:07:47.849577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from backend.app.core.database import GUID



# revision identifiers, used by Alembic.
revision: str = 'c8b5c0cd3cf0'
down_revision: Union[str, Sequence[str], None] = 'e0ae5104d8d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('concept', schema=None) as batch_op:
         batch_op.create_index(batch_op.f('ix_concept_name'), ['name'], unique=True)
 
    op.create_table('knowledge_connection',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('source_id', GUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', GUID(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('connection_type', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_connection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_connection_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_connection_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_connection_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_connection_target_type'), ['target_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_connection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_connection_target_type'))
        batch_op.drop_index(batch_op.f('ix_knowledge_connection_target_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_connection_source_type'))
        batch_op.drop_index(batch_op.f('ix_knowledge_connection_source_id'))

    op.drop_table('knowledge_connection')
    with op.batch_alter_table('concept', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concept_name'))

    op.drop_table('concept')
    # ### end Alembic commands ###
