"""create_embedding_record_table

Revision ID: d326487bc9ca
Revises: ea6f68f33781
Create Date: 2026-05-30 11:59:01.519221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import backend
import backend.app.core.database



# revision identifiers, used by Alembic.
revision: str = 'd326487bc9ca'
down_revision: Union[str, Sequence[str], None] = 'ea6f68f33781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_record',
    sa.Column('id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('entity_id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('hash_content', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('embedding_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_embedding_record_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_embedding_record_entity_type'), ['entity_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embedding_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_embedding_record_entity_type'))
        batch_op.drop_index(batch_op.f('ix_embedding_record_entity_id'))

    op.drop_table('embedding_record')
    # ### end Alembic commands ###
