"""Initial JTI models creation

Revision ID: dc7034d6ba93
Revises: 
Create Date: 2026-05-30 11:39:32.438962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import backend
import backend.app.core.database


# revision identifiers, used by Alembic.
revision: str = 'dc7034d6ba93'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_resource',
    sa.Column('id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('cover_path', sa.String(length=512), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='resourcestatus'), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_resource', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_resource_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_resource_title'), ['title'], unique=False)

    op.create_table('book',
    sa.Column('id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('reading_percentage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['learning_resource.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_author'), ['author'], unique=False)

    op.create_table('course',
    sa.Column('id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('difficulty', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='coursedifficulty'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['learning_resource.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_session',
    sa.Column('id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('resource_id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['learning_resource.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('module',
    sa.Column('id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('course_id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('course_id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson',
    sa.Column('id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('module_id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('lesson_type', sa.Enum('VIDEO', 'PDF', 'EPUB', 'ARTICLE', 'PROJECT', name='lessontype'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note',
    sa.Column('id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('resource_id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('lesson_id', backend.app.core.database.GUID(), nullable=True),
    sa.Column('content', sa.String(length=5000), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['learning_resource.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    op.drop_table('lesson')
    op.drop_table('task')
    op.drop_table('module')
    op.drop_table('learning_session')
    op.drop_table('course')
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_author'))

    op.drop_table('book')
    with op.batch_alter_table('learning_resource', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_resource_title'))
        batch_op.drop_index(batch_op.f('ix_learning_resource_category'))

    op.drop_table('learning_resource')
    # ### end Alembic commands ###
