"""create_content_intelligence_tables

Revision ID: ea6f68f33781
Revises: c15454b31b32
Create Date: 2026-05-30 11:56:26.953636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import backend
import backend.app.core.database



# revision identifiers, used by Alembic.
revision: str = 'ea6f68f33781'
down_revision: Union[str, Sequence[str], None] = 'c15454b31b32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_index',
    sa.Column('id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('media_asset_id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('section_identifier', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_metadata',
    sa.Column('id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('media_asset_id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('toc', sa.JSON(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_asset_id')
    )
    op.create_table('transcript',
    sa.Column('id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('media_asset_id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_asset_id')
    )
    op.create_table('transcript_segment',
    sa.Column('id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('transcript_id', backend.app.core.database.GUID(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcript.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcript_segment')
    op.drop_table('transcript')
    op.drop_table('extracted_metadata')
    op.drop_table('content_index')
    # ### end Alembic commands ###
