"""
Pydantic models for AI responses.
Used with LangChain's structured output for type-safe LLM responses.
"""
from pydantic import BaseModel, Field
from typing import Optional, Literal


class QuizQuestion(BaseModel):
    """A single quiz question generated by the LLM."""
    id: str = Field(description="Unique question identifier (e.g., 'q1')")
    question: str = Field(description="The question text")
    options: list[str] = Field(default_factory=list, description="Answer options for multiple choice")
    answer: str = Field(description="The correct answer")
    type: Literal["multiple_choice", "short_answer"] = Field(
        description="Question type"
    )


class TutorResponse(BaseModel):
    """Structured response from the AI tutor."""
    answer: str = Field(description="The tutor's answer to the student's question")
    sources: list[str] = Field(default_factory=list, description="Source snippets used")


class ConceptCheck(BaseModel):
    """A concept-check question for spaced repetition review."""
    question: str = Field(description="The verification question")
    guide: str = Field(description="Brief answer guide in brackets")


class SummaryResponse(BaseModel):
    """A summarized version of study notes."""
    summary: str = Field(description="The condensed summary in Markdown")


class FlashcardSet(BaseModel):
    """A set of flashcards generated from content."""
    flashcards: list["Flashcard"] = Field(description="List of flashcards")


class Flashcard(BaseModel):
    """A single flashcard with question and answer."""
    front: str = Field(description="The question or prompt")
    back: str = Field(description="The answer or explanation")
